Game\CoreBundle\Entity\User:
    properties:
        username:
            - NotBlank:
                message: Login must be not blank.
            - Length:
                min: 5
                max: 25
                minMessage: Login must be at least 5 characters.
                maxMessage: Login must be max 25 characters.
        password:
            - NotBlank:
                message: Password must be not blank.
            - Length:
                min: 5
                max: 40
                minMessage: Password must be at least 5 characters.
                maxMessage: Password must be max 40 characters.