# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

_welcome:
    pattern:  /
    defaults: { _controller: GameCoreBundle:Welcome:index }

_initResources:
    pattern:  /resources/
    defaults: { _controller: GameCoreBundle:Resources:init }

_do:
    pattern:  /action/{action}
    defaults: { _controller: GameCoreBundle:Do:index, action: ''}

_admin:
    pattern:  /admin/
    defaults: { _controller: GameCoreBundle:Admin:index}

_mapEditor:
    pattern: /map/
    defaults: { _controller: GameCoreBundle:MapEditor:index}

login:
    pattern:   /login
    defaults:  { _controller: GameCoreBundle:Security:login }

register:
    pattern:   /register
    defaults:  { _controller: GameCoreBundle:Security:register }

login_check:
    pattern:   /login_check
logout:
    pattern:   /logout

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

facebook_login:
    pattern: /login/check-facebook