jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Game\CoreBundle\Entity\User: plaintext
        HWI\Bundle\OAuthBundle\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        oauth_user_provider:
          id: memory_oauth_user_provider
        main:
          entity: { class: Game\CoreBundle\Entity\User, property: username }

    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                provider: main
                login_path: /login
                check_path: /login_check
                success_handler: game_core_security.auth.handler.login_success_handler
                #logout_path: /logout
            oauth:
                resource_owners:
                    facebook:           "/login/check-facebook"
                login_path:        /login
                failure_path:      /login
                success_handler: game_core_security.auth.handler.login_success_handler
                oauth_user_provider:
                    oauth: ~

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_USER }
        - { path: ^/map, roles: ROLE_USER }
