jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Game\CoreBundle\Entity\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: Game\CoreBundle\Entity\User, property: username }

    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  /login
                check_path:  /login_check
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/admin, roles: ROLE_USER }
        - { path: ^/map, roles: ROLE_USER }
